name: Release Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (semver, e.g. 1.0.1)'
        required: true
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project: [
          ./ATM/ATM.Domain/ATM.Domain.csproj,
          ./Payment/Payment.Domain/Payment.Domain.csproj
        ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Determine version
        id: v
        run: |
          if [ -n "${{ github.event.inputs.version }}" ]; then
            ver=${{ github.event.inputs.version }}
          else
            tag=${GITHUB_REF#refs/tags/}
            ver=${tag#v}   # elimina la 'v' inicial del tag
          fi
          echo "Setting version to $ver"
          echo "ver=$ver" >> $GITHUB_OUTPUT
          echo "ver=$ver" >> $GITHUB_ENV   # ðŸ”¹ agrega compatibilidad entre steps

      - name: Update csproj version
        run: |
          echo "Updating version in ${{ matrix.project }} to $ver"
          sed -i "s#<Version>.*</Version>#<Version>$ver</Version>#" ${{ matrix.project }}
          grep -n "<Version>" ${{ matrix.project }}

      - name: Build Release
        run: dotnet build ${{ matrix.project }} -c Release

      - name: Pack
        run: dotnet pack ${{ matrix.project }} -c Release -o out /p:PackageVersion=$ver /p:Version=$ver

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.ver }}
          name: Release v${{ env.ver }}
          draft: false
          prerelease: false
          files: |
            out/*.nupkg
            out/*.snupkg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
